name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          dsf:
            - 'dsf-gdb/**'
            - 'dsf/**'
            - 'debug/**'
            - 'jtag/**'
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - name: Install GCC & GDB & other build essentials
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential gcc g++ gdb gdbserver
        gdb --version
        gcc --version
        gdbserver --version
    - name: Build and Test
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        echo 0| sudo tee /proc/sys/kernel/yama/ptrace_scope
        mvn \
          clean verify -B -V \
          -Dmaven.test.failure.ignore=true \
          -DexcludedGroups=flakyTest,slowTest \
          -Ddsf.gdb.tests.timeout.multiplier=50 \
          -Ddsf-gdb.skip.tests=$(test ${{ steps.filter.outputs.dsf }} == 'false' && echo 'true' || echo 'false') \
          -Dindexer.timeout=300
    - name: Upload Logs
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Code Cleanliness Detailed Logs
        path: '*.log'
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: |
          */*/target/surefire-reports/*.xml
          terminal/plugins/org.eclipse.tm.terminal.test/target/surefire-reports/*.xml
